---
 environment: production
 chdir: /home/lightsaber/lightsaber/current
 address: 0.0.0.0
 user: lightsaber
 group: lightsaber
 port: 4567
 pid: /tmp/lightsaber.pid
 rackup: config.ru
 log: /home/lightsaber/lightsaber/thin.log
 max_conns: 1024
 timeout: 5
 max_persistent_conns: 256
 daemonize: true